### ISSUE TITLE
Title does not look well on small screens 

### ISSUE THREAD

**Issue by igorkulman** [cssandstuff/hugo-theme-winning#6]
Screenshot from iPhone 6S

![3c78f7b0-f3da-45ae-a2ca-68fce0fe49fe](https://user-images.githubusercontent.com/4746070/50797832-6814b680-12d6-11e9-82ab-8593b360b3f1.png)

**Comment by emansom** [comment]
What browser and iOS version?

**Comment by igorkulman** [comment]
My device is iPhone 6S on iOS 12.1.2. The screenshot is from Firefox Focus but the title is broken in the same way in Safari.

**Comment by igorkulman** [comment]
I can also reproduce in Safari on any iOS 12.1 simulator, this is iPhone X

![simulator screen shot - iphone x - 2019-01-08 at 09 50 31](https://user-images.githubusercontent.com/4746070/50819635-f155d880-132a-11e9-8fc3-3c39eb726580.png)

**Comment by cssandstuff** [comment]
Have changed the line-height to accommodate.
<img width="390" alt="screenshot 2019-01-08 22 21 58" src="https://user-images.githubusercontent.com/3496246/50821383-edaa6c00-1393-11e9-97bb-430bb8e7af32.png">

**Comment by igorkulman** [comment]
Looks ok now, thanks.
